# Sample EPP configuration for tunning with P/D
# Use with small hash block size for simulation purposes
apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: EndpointPickerConfig
featureGates:
- prepareDataPlugins
plugins:
- type: encoder-header-handler
- type: queue-scorer
- type: encode-filter
- type: decode-filter
- type: always-encode-decider
- type: ed-profile-handler
  parameters:
    primaryPort: ${PRIMARY_PORT}
    deciderPluginName: always-encode-decider
schedulingProfiles:
- name: encode
  plugins:
  - pluginRef: encode-filter
    weight: 2
- name: decode
  plugins:
  - pluginRef: decode-filter
  - pluginRef: queue-scorer
    weight: 1
