# ------------------------------------------------------------------------------
# Kubernetes In Docker (KIND) Environment
#
# This will deploy the full development stack on a KIND cluster:
#
#  * Istio Control Plane
#  * Real VLLM (EPD mode)
#  * Inference Gateway
#
# This will expose real VLLM via InferencePool and an HTTPRoute.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base-kind-istio/
- ../../../components/vllm-sim-epd-real-vllm/
