name: Label non-main PRs

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels when base branch is not main
        if: github.event.pull_request.base.ref != 'main'
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            do-not-merge/hold
